### PR TITLE
Always use `var` and `undefined` for `new`-based constructors

### LINKED ISSUE #624: Consistently set defaults for `new`-based constructors
`MutationObserverInit` is defined as a trait with vars and initial values, thus doing this won't compile:

```scala
new MutationObserverInit {
  val childList: UndefOr[Boolean] = someChildList
  ...
```

As a slight inconvenience, because the fields are initialized in the trait, the `override` modifier is required. 
But what doesn't work is overriding the vars: `scalac` complains `mutable variable cannot be overridden`.

### PR DESCRIPTION
**Pull request by armanbilge**
Fixes #624. I went through all of the -`Init` classes and checked that they are using `var` and `js.undefined` as their default value. Are there non-`Init` classes that we should check too?

### CODE REVIEW

File: dom/src/main/scala/org/scalajs/dom/ResponseInit.scala [hunk 1]
```diff
@@ -4,7 +4,7 @@ import scala.scalajs.js
 
 /** See [[https://fetch.spec.whatwg.org/#response-class ¶6.4 Response class]] definition in whatwg Fetch spec. */
 trait ResponseInit extends js.Object {
-  var status: Int
-  var statusText: ByteString
-  var headers: HeadersInit
+  var status: js.UndefOr[Int] = js.undefined
+  var statusText: js.UndefOr[ByteString] = js.undefined
+  var headers: js.UndefOr[HeadersInit] = js.undefined
 }
```
Comment (armanbilge) [inline dom/src/main/scala/org/scalajs/dom/ResponseInit.scala:10]: @sjrd is changing these return signatures ok for bincompat? I realized I don't know what the semantics are for `js.Object`.

**Comment by armanbilge** [comment]
Oh btw, would everyone be okay with releasing v2.1.0 shortly after we merge this PR? I may fix another open issue or two but not really a priority. Feel free to point out any that are important.

File: dom/src/main/scala/org/scalajs/dom/ResponseInit.scala (hunk 1 above)
Comment (sjrd) [reply dom/src/main/scala/org/scalajs/dom/ResponseInit.scala:10]: Yes, this is fine.

**Review by sjrd — APPROVED** [review]
