### PR TITLE
Fix #219: Fix Event constructors.

### LINKED ISSUE #219: Invalid Event constructor
This:

``` scala
new org.scalajs.dom.Event
```

breaks FireFox with

```
TypeError: Not enough arguments to Event.
```

Spec shows it should be: https://developer.mozilla.org/en-US/docs/Web/API/Event/Event

### PR DESCRIPTION
**Pull request by exoego**
Closes #219

* Add valid constructors that accept type name and init, as well as type-safe constructor options `***EventInit`
* Removes invalid default (0 args) constructors since `new ***Event()` raises RuntimeError due to lack of required argument
* Add `@deprecated` based on MDN

### CODE REVIEW

File: src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala [hunk 1]
```diff
@@ -917,16 +925,20 @@ class RTCPeerConnection(
...
+//   * event is sent when a MediaStream is added to this connection by the
+//   * remote peer. The event is sent immediately after the call
+//   * RTCPeerConnection.setRemoteDescription() and doesn't wait for the result
+//   * of the SDP negotiation.
+//   *
+//   * MDN
+//   */
+// TODO: Delete or giving up fatal-warning?
+//  @deprecated("Deprecated in favor of ontrack", "0.9.8")
+//  var onaddstream: js.Function1[MediaStreamEvent, Any] = js.native
```
Comment (sjrd) [inline src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala]: Why is this commented out?

File: src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala [hunk 2]
```diff
@@ -997,13 +1009,16 @@ class RTCPeerConnection(
...
-  var onremovestream: js.Function1[MediaStreamEvent, Any] = js.native
+//  /**
+//   * Is the event handler called when the removestream event, sent when a
+//   * MediaStream is removed from this connection, is received.
+//   *
+//   * MDN
+//   */
+  // TODO: Delete or giving up fatal-warning?
+  //  @deprecated("Deprecated in favor of onremovetrack", "0.9.8")
+  //  var onremovestream: js.Function1[MediaStreamEvent, Any] = js.native
```
Comment (sjrd) [inline src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala]: Why is this commented out?

File: src/main/scala/org/scalajs/dom/raw/lib.scala [hunk 3]
```diff
@@ -3519,6 +3553,12 @@ abstract class Document
   def releaseCapture(): Unit = js.native
 }
 
+trait MessageEventInit extends EventInit {
+  var source: js.UndefOr[Window] = js.undefined
+  var origin: js.UndefOr[String] = js.undefined
+  var data: js.UndefOr[String | Blob | ArrayBuffer] = js.undefined
```
Comment (sjrd) [inline src/main/scala/org/scalajs/dom/raw/lib.scala]: MDN says that `data` can be any data type, so this should be `js.UndefOr[Any]`.

File: src/main/scala/org/scalajs/dom/raw/lib.scala [hunk 4]
```diff
@@ -3538,12 +3579,13 @@ class MessageEvent extends Event {
    *
    * MDN
    */
-  def data: Any = js.native
+  def data: String | Blob | ArrayBuffer = js.native
```
Comment (sjrd) [inline src/main/scala/org/scalajs/dom/raw/lib.scala]: MDN says that `data` can be any data type, so this should stay `Any`.

File: src/main/scala/org/scalajs/dom/raw/lib.scala [hunk 5]
```diff
@@ -3538,12 +3579,13 @@ class MessageEvent extends Event {
...
 
   @deprecated("Non-standard", "forever")
   def initMessageEvent(typeArg: String, canBubbleArg: Boolean,
-      cancelableArg: Boolean, dataArg: js.Any, originArg: String,
-      lastEventIdArg: String, sourceArg: Window): Unit = js.native
+      cancelableArg: Boolean, dataArg: String | Blob | ArrayBuffer,
```
Comment (sjrd) [inline src/main/scala/org/scalajs/dom/raw/lib.scala]: This should probably be `Any` as well.

File: src/main/scala/org/scalajs/dom/raw/lib.scala [hunk 6]
```diff
@@ -5648,14 +5718,19 @@ class StyleSheetList extends js.Object {
   def update(index: Int, v: StyleSheet): Unit = js.native
 }
 
+trait CustomEventInit extends EventInit {
+  var detailArg: js.UndefOr[js.Any] = js.undefined
```
Comment (sjrd) [inline src/main/scala/org/scalajs/dom/raw/lib.scala]: I am pretty sure this should an `Any` as well.

File: src/main/scala/org/scalajs/dom/raw/lib.scala [hunk 7]
```diff
@@ -5851,10 +5927,17 @@ class TimeRanges extends js.Object {
 
 @js.native
 @JSGlobal
-class BeforeUnloadEvent extends Event {
+class BeforeUnloadEvent extends Event("") {
```
Comment (sjrd) [inline src/main/scala/org/scalajs/dom/raw/lib.scala]: It is more customary to use `js.native` as the arguments to another argument, in order to be confused that `""` is not actually taken into account.

File: src/main/scala/org/scalajs/dom/raw/lib.scala [hunk 8]
```diff
@@ -4829,8 +4829,7 @@ trait MutationEventInit extends EventInit {
     "WHATWG DOM")
 @js.native
 @JSGlobal
-class MutationEvent(typeArg: String, init: js.UndefOr[MutationEventInit])
-    extends Event(typeArg, init) {
+class MutationEvent extends Event("", js.undefined) {
```
Comment (sjrd) [inline src/main/scala/org/scalajs/dom/raw/lib.scala]: If it has no constructor, its constructor should be marked `private`. Otherwise there is nothing preventing to do `new MutationEvent` from the Scala side (with a run-time error).

File: src/main/scala/org/scalajs/dom/experimental/deviceorientation/DeviceOrientation.scala [hunk 9]
```diff
@@ -29,23 +28,23 @@ class DeviceOrientationEvent(
   val absolute: Boolean = js.native
 }
 
-trait DeviceOrientationEventInit extends js.Object {
+trait DeviceOrientationEventInit extends dom.raw.EventInit {
```
[the remark this answers is not in the document]
Comment (exoego) [reply src/main/scala/org/scalajs/dom/experimental/deviceorientation/DeviceOrientation.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/882c07929a702ff6b4e740dae9ba3a06de7d930a

File: src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala [hunk 10]
```diff
@@ -79,6 +80,12 @@ trait Client extends js.Object {
 trait CanvasProxy extends js.Any {
   def setContext(context: RenderingContext): Unit = js.native
 }
+trait FetchEventInit extends EventInit {
```
[the remark this answers is not in the document]
Comment (exoego) [reply src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/dde36b29432a54f33959ef15afa9f46713efccfa

File: src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala [hunk 11]
```diff
@@ -382,8 +398,9 @@ trait ServiceWorkerContainer extends EventTarget {
    *
    * MDN
    */
-  var onmessage: js.Function1[ServiceWorkerMessageEvent, _] = js.native
+  var onmessage: js.Function1[MessageEvent, _] = js.native
 }
+trait ExtendableEventInit extends EventInit {}
```
[the remark this answers is not in the document]
Comment (exoego) [reply src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/dde36b29432a54f33959ef15afa9f46713efccfa

File: src/main/scala/org/scalajs/dom/raw/lib.scala (hunk 6 above)
Comment (exoego) [reply src/main/scala/org/scalajs/dom/raw/lib.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/44578113bd8c569bf68e9c1c5cfdc484d49df12a

File: src/main/scala/org/scalajs/dom/raw/lib.scala (hunk 5 above)
Comment (exoego) [reply src/main/scala/org/scalajs/dom/raw/lib.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/44578113bd8c569bf68e9c1c5cfdc484d49df12a

File: src/main/scala/org/scalajs/dom/raw/lib.scala (hunk 4 above)
Comment (exoego) [reply src/main/scala/org/scalajs/dom/raw/lib.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/44578113bd8c569bf68e9c1c5cfdc484d49df12a

File: src/main/scala/org/scalajs/dom/raw/lib.scala (hunk 3 above)
Comment (exoego) [reply src/main/scala/org/scalajs/dom/raw/lib.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/44578113bd8c569bf68e9c1c5cfdc484d49df12a

File: src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala (hunk 1 above)
Comment (exoego) [reply src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala]: Because usage of deprecated class `MediaStreamEvent` raises error, since it is strictly forbidden by compiler options `deprecation` and `fatal-warning`.

I think we have 2 options.

1. Remove (or comment out) the menbers `onaddstream` and `onremovestream`.
2. Giving up `fatal-warning`.

File: src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala (hunk 2 above)
Comment (exoego) [reply src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala]: Same as https://github.com/scala-js/scala-js-dom/pull/367#discussion_r284477765

File: src/main/scala/org/scalajs/dom/raw/lib.scala (hunk 8 above)
Comment (exoego) [reply src/main/scala/org/scalajs/dom/raw/lib.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/879d4ae4a821add24c1e96333666a22781349c3c

Used `private[this]` instead of `private()`,  thanks to deprecation warning ```declaring private constructors in native JS classes is deprecated, because they do not behave the same way as in Scala.js-defined JS classes.  Use `private[this]` instead. This will become an error in 1.0.0.```

File: src/main/scala/org/scalajs/dom/raw/lib.scala (hunk 7 above)
Comment (exoego) [reply src/main/scala/org/scalajs/dom/raw/lib.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/b7194a5e0762274b1161e67ea8ae9b4bc7a3e331

File: src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala [hunk 12]
```diff
@@ -449,17 +466,12 @@ class ExtendableMessageEvent(`type`: String,
...
-
-  var origin: String = js.native
-
-  var lastEventId: String = js.native
-
-  var source: ServiceWorker | MessagePort = js.native
-
-  var ports: js.Array[MessagePort] = js.native
+trait ServiceWorkerMessageEventInit extends EventInit {
+  var data: js.UndefOr[js.Any] = js.undefined
```
[the remark this answers is not in the document]
Comment (exoego) [reply src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala]: Fixed in https://github.com/scala-js/scala-js-dom/pull/367/commits/7f987573a88ae9a8779da25f60d2da71fcb6b8e5

File: src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala (hunk 1 above)
Comment (sjrd) [reply src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala]: I see. I'm not sure why scalac reports a warning, given that the `var` is deprecated itself. Apparently it has to do with it being a `var`. You can work around the issue by defining a getter and setter separately, as follows:
```scala
  @deprecated("Deprecated in favor of onremovetrack", "0.9.8")
  def onremovestream: js.Function1[MediaStreamEvent, Any] = js.native

  @deprecated("Deprecated in favor of onremovetrack", "0.9.8")
  def onremovestream_(v: js.Function1[MediaStreamEvent, Any]): Unit = js.native
```

Comment (exoego) [reply src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala]: Ah, neat trick.
Done in https://github.com/scala-js/scala-js-dom/pull/367/commits/9e80c810a91bc58aefd51841e5feca6308a5e5f0

File: src/main/scala/org/scalajs/dom/raw/lib.scala [hunk 13]
```diff
@@ -4772,10 +4822,15 @@ abstract class DocumentType extends Node {
   def publicId: String = js.native
 }
 
-@deprecated("Obsolete.", "WHATWG DOM")
+trait MutationEventInit extends EventInit {
```
Comment (sjrd) [inline src/main/scala/org/scalajs/dom/raw/lib.scala]: Do we still need this definition? Couldn't we just not define it at all?

Comment (exoego) [reply src/main/scala/org/scalajs/dom/raw/lib.scala]: Removed in https://github.com/scala-js/scala-js-dom/pull/367/commits/96938be30d8c2725a64f61feede2f09a4d0dd54d
